Repository databrickslabs/ucx, pull requests merged in 2023-10, with the labels that each got.

#307 Define table migration process
  docs/table_upgrade.md
Labels: to be discussed, component:lookup

#306 Added a column to `$inventory.tables` to specify if a table might have been synchronised to Unity Catalog already or not
  docs/table_persistence.md
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/tables.scala
  tests/unit/hive_metastore/test_tables.py
Labels: enhancement, do-not-merge

#375 Improved cleanup for workspace backup groups by adding more retries on errors
  docs/local-group-migration.md
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/generic.py
  src/databricks/labs/ucx/workspace_access/groups.py
  src/databricks/labs/ucx/workspace_access/scim.py
  tests/integration/test_installation.py
  tests/unit/workspace_access/test_generic.py
  tests/unit/workspace_access/test_groups.py
Labels: step:migrate groups

#412 Added support for migrating Legacy Table ACLs from workspace-local to account-level groups
  README.md
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/base.py
  src/databricks/labs/ucx/workspace_access/groups.py
  src/databricks/labs/ucx/workspace_access/manager.py
  src/databricks/labs/ucx/workspace_access/migration.py
  src/databricks/labs/ucx/workspace_access/tacl.py
  tests/integration/test_installation.py
  tests/integration/workspace_access/test_workspace_access.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/workspace_access/test_tacl.py
Labels: enhancement, step:migrate groups

#442 Split `migrate-groups` workflow into three different stages for reliability
  src/databricks/labs/ucx/mixins/fixtures.py
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/integration/test_installation.py
Labels: do-not-merge

#481 Fixed issue with workspace listing process on None type object_type
  src/databricks/labs/ucx/workspace_access/generic.py
  tests/unit/workspace_access/test_generic.py
Labels: bug, crawler

#487 Running apply permission task before assessment should display message
  src/databricks/labs/ucx/workspace_access/manager.py
  tests/unit/workspace_access/test_manager.py
Labels: bug, ready to merge, step:migrate groups

#400 Added support for external Hive Metastores including AWS Glue
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/install.py
  tests/unit/test_config.py
  tests/unit/test_install.py
Labels: crawler, step:migrate groups, step:sync tables, step:assign metastore, step:upgrade dbsql, step:upgrade clusters, installer

#473 Added documentation to describe interaction with external Hive Metastores
  docs/external_hms.md
Labels: documentation, crawler, step:migrate groups, step:assessment, step:assign metastore, step:upgrade dbsql, step:upgrade clusters, installer, component:lookup
