Repository databrickslabs/ucx, pull requests merged in 2023-09, with the labels that each got.

#204 Add `codecov.io` publishing
  .github/workflows/push.yml
Labels: do-not-merge

#214 Create dashboards on installation and require `warehouse_id` on installation
  src/databricks/labs/ucx/assessment/queries/total_tables.sql
  src/databricks/labs/ucx/assessment/queries/workspace_access_total_groups.sql
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/framework/dashboards.py
  src/databricks/labs/ucx/framework/tasks.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/mixins/fixtures.py
  src/databricks/labs/ucx/runtime.py
  tests/integration/conftest.py
  tests/integration/test_installation.py
  tests/unit/test_install.py
Labels: enhancement

#269 Update existing and add new SQL queries to the assessment step dashboard
  src/databricks/labs/ucx/assessment/queries/all_tables.sql
  src/databricks/labs/ucx/assessment/queries/clusters.sql
  src/databricks/labs/ucx/assessment/queries/count_total_databases.sql
  src/databricks/labs/ucx/assessment/queries/count_total_tables.sql
  src/databricks/labs/ucx/assessment/queries/database_summary.sql
  src/databricks/labs/ucx/assessment/queries/external_locations.sql
  src/databricks/labs/ucx/assessment/queries/jobs.sql
  src/databricks/labs/ucx/assessment/queries/mount_points.sql
  src/databricks/labs/ucx/assessment/queries/total_tables.sql
  src/databricks/labs/ucx/assessment/queries/workspace_access_total_groups.sql
  src/databricks/labs/ucx/framework/dashboards.py
  tests/integration/framework/test_dashboards.py
Labels: enhancement

#264 Add support for account-level configuration and multi-cloud workspace list
  notebooks/toolkit.py
  src/databricks/labs/ucx/account/__init__.py
  src/databricks/labs/ucx/account/workspaces.py
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/framework/tasks.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/migration.py
  tests/integration/hive_metastore/test_mounts.py
  tests/integration/test_installation.py
  tests/integration/workspace_access/test_workspace_access.py
  tests/unit/account/__init__.py
  tests/unit/account/test_workspaces.py
  tests/unit/test_config.py
  tests/unit/test_install.py
Labels: account-level work

#325 Added a migration state to skip already migrated tables
  src/databricks/labs/ucx/hive_metastore/tables.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_migrate.py
  tests/unit/hive_metastore/test_migrate.py
Labels: step:managed tables

#345 Ported internal document about UCX persistence schema
  docs/table_persistence.md
Labels: documentation
