Repository databrickslabs/ucx, pull requests merged in 2023-11, with the labels that each got.

#513 Install a global init script to collect HMS lineage for a few weeks.
  src/databricks/labs/ucx/hive_metastore/hms_lineage.py
  src/databricks/labs/ucx/hive_metastore/hms_lineage_global_init_script.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/runtime.py
  tests/unit/hive_metastore/test_hms_lineage.py
  tests/unit/test_install.py
Labels: ready to merge

#571 Fix/table owner permission 558
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/workspace_access/tacl.py
  tests/integration/workspace_access/test_groups.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/workspace_access/test_tacl.py
Labels: ready to merge

#450 Use `ws.groups.patch` to rename groups instead of creating backup groups
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/base.py
  src/databricks/labs/ucx/workspace_access/generic.py
  src/databricks/labs/ucx/workspace_access/groups.py
  src/databricks/labs/ucx/workspace_access/manager.py
  src/databricks/labs/ucx/workspace_access/migration.py
  src/databricks/labs/ucx/workspace_access/redash.py
  src/databricks/labs/ucx/workspace_access/scim.py
  src/databricks/labs/ucx/workspace_access/secrets.py
  src/databricks/labs/ucx/workspace_access/tacl.py
  src/databricks/labs/ucx/workspace_access/verification.py
  tests/integration/conftest.py
  tests/integration/test_installation.py
  tests/integration/workspace_access/test_groups.py
  tests/integration/workspace_access/test_scim.py
  tests/integration/workspace_access/test_workspace_access.py
  tests/unit/assessment/test_dashboard.py
  tests/unit/test_config.py
  tests/unit/test_install.py
  tests/unit/workspace_access/conftest.py
  tests/unit/workspace_access/test_base.py
  tests/unit/workspace_access/test_generic.py
  tests/unit/workspace_access/test_groups.py
  tests/unit/workspace_access/test_manager.py
  tests/unit/workspace_access/test_redash.py
  tests/unit/workspace_access/test_scim.py
  tests/unit/workspace_access/test_secrets.py
  tests/unit/workspace_access/test_tacl.py
Labels: crawler, step:migrate groups, breaking change

#600 Fixed install check for git pre-release versions
  src/databricks/labs/ucx/install.py
Labels: ready to merge

#614 Updated tables.scala to read inventory database from config.yml file
  src/databricks/labs/ucx/hive_metastore/tables.scala
  src/databricks/labs/ucx/install.py
Labels: ready to merge

#566 Added current version of UCX to task logs
  src/databricks/labs/ucx/framework/tasks.py
Labels: do-not-merge, cla-required

#621 Fixed External Location widget to return hostname for `jdbc:` locations
  src/databricks/labs/ucx/hive_metastore/data_objects.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/tables.scala
  tests/integration/hive_metastore/test_external_locations.py
  tests/unit/assessment/test_assessment.py
Labels: ready to merge, breaking change
