Repository databrickslabs/ucx, pull requests merged in 2024-03, with the labels that each got.

#995 Added group members difference to the output of validate-groups-membership cli command
  labs.yml
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/unit/workspace_access/test_groups.py
Labels: ready to merge

#997 Added permission migration support for feature tables and the root permissions for models and feature tables
  src/databricks/labs/ucx/mixins/fixtures.py
  src/databricks/labs/ucx/workspace_access/generic.py
  src/databricks/labs/ucx/workspace_access/manager.py
  tests/integration/workspace_access/test_generic.py
  tests/unit/workspace_access/test_generic.py
  tests/unit/workspace_access/test_manager.py
Labels: ready to merge

#989 Add database filter for the `assessment` workflow
  README.md
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/table_size.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/tables.scala
  src/databricks/labs/ucx/hive_metastore/udfs.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/runtime.py
  tests/integration/hive_metastore/test_tables.py
  tests/integration/hive_metastore/test_udfs.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/hive_metastore/test_tables.py
  tests/unit/hive_metastore/test_udfs.py
  tests/unit/test_install.py
  tests/unit/test_runtime.py
Labels: ready to merge, step:assessment

#960 Added crawling for init scripts on local files to assessment workflow
  src/databricks/labs/ucx/assessment/clusters.py
  src/databricks/labs/ucx/assessment/crawlers.py
  tests/unit/assessment/clusters/init-scripts-file.json
  tests/unit/assessment/clusters/init-scripts-no-match.json
  tests/unit/assessment/test_clusters.py
Labels: ready to merge, step:assessment

#973 Added AWS IAM roles support to `databricks labs ucx migrate-credentials` command
  src/databricks/labs/ucx/assessment/aws.py
  src/databricks/labs/ucx/aws/__init__.py
  src/databricks/labs/ucx/aws/credentials.py
  src/databricks/labs/ucx/azure/credentials.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/mixins/fixtures.py
  tests/integration/assessment/test_aws.py
  tests/integration/aws/__init__.py
  tests/integration/aws/test_credentials.py
  tests/integration/azure/test_credentials.py
  tests/unit/__init__.py
  tests/unit/assessment/test_aws.py
  tests/unit/aws/__init__.py
  tests/unit/aws/test_credentials.py
  tests/unit/azure/test_credentials.py
  tests/unit/test_cli.py
Labels: ready to merge

#1008 Estimate migration effort based on assessment database
  src/databricks/labs/ucx/framework/dashboards.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/queries/assessment/estimates/00_0_metastore_assignment.md
  src/databricks/labs/ucx/queries/assessment/estimates/00_2_is_metastore_assigned.sql
  src/databricks/labs/ucx/queries/assessment/estimates/00_4_is_incompatible_submit_run_detected.sql
  src/databricks/labs/ucx/queries/assessment/estimates/01_0_group_migration.md
  src/databricks/labs/ucx/queries/assessment/estimates/01_2_group_migration.sql
  src/databricks/labs/ucx/queries/assessment/estimates/01_5_group_migration_complexity.sql
  src/databricks/labs/ucx/queries/assessment/estimates/02_0_data_modeling.md
  src/databricks/labs/ucx/queries/assessment/estimates/02_2_uc_data_modeling.sql
  src/databricks/labs/ucx/queries/assessment/estimates/02_5_uc_data_modeling_complexity.sql
  src/databricks/labs/ucx/queries/assessment/estimates/03_0_data_migration.md
  src/databricks/labs/ucx/queries/assessment/estimates/03_2_data_migration_summary.sql
  src/databricks/labs/ucx/queries/assessment/estimates/03_5_data_migration_complexity.sql
  src/databricks/labs/ucx/queries/views/table_estimates.sql
  src/databricks/labs/ucx/runtime.py
  tests/unit/test_install.py
Labels: ready to merge

#1024 Added automated upgrade option to set up cluster policy
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/installer/policy.py
  src/databricks/labs/ucx/upgrades/v0.15.0_added_cluster_policy.py
  tests/unit/installer/test_policy.py
  tests/unit/test_install.py
Labels: ready to merge

#1026 Added integration tests for AWS - create locations
  src/databricks/labs/ucx/assessment/aws.py
  tests/integration/assessment/test_aws.py
  tests/unit/assessment/test_aws.py
  tests/unit/test_cli.py
Labels: ready to merge

#1019 Increased test coverage for verification suite
  tests/unit/workspace_access/test_verification.py
Labels: ready to merge

#854 Changed default UCX installation folder to `/Applications/ucx` from `/Users/<me>/.ucx` to allow multiple users users utilising the same installation
  README.md
  pyproject.toml
  src/databricks/labs/ucx/install.py
  tests/integration/test_installation.py
  tests/unit/assessment/test_dashboard.py
  tests/unit/test_install.py
Labels: installer

#1041 Added `migration_status` table to capture a snapshot of migrated tables
  src/databricks/labs/ucx/framework/crawlers.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/install.py
  tests/integration/hive_metastore/test_migrate.py
  tests/unit/hive_metastore/test_table_migrate.py
Labels: breaking change

#1013 Added Dashboard widget to show the list of cluster policies along with DBR version
  src/databricks/labs/ucx/assessment/clusters.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/mixins/fixtures.py
  src/databricks/labs/ucx/queries/assessment/main/08_0_cluster_policies.sql
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/upgrades/v0.16.0_changing_cluster_table_schema.py
  tests/integration/assessment/test_clusters.py
  tests/unit/assessment/__init__.py
  tests/unit/assessment/policies/single-user-with-spn-no-sparkversion.json
  tests/unit/assessment/policies/single-user-with-spn-policyid.json
  tests/unit/assessment/test_clusters.py
Labels: breaking change

#1046 Add a check for external metastore in SQL warehouse configuration
  src/databricks/labs/ucx/installer/policy.py
  tests/unit/installer/test_policy.py
Labels: ready to merge

#1056 Refactored `workspace_client_mock` to use `installation.load()`
  src/databricks/labs/ucx/hive_metastore/mapping.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  tests/unit/__init__.py
  tests/unit/assessment/clusters/policy-single-user-with-empty-appid-spn.json
  tests/unit/assessment/clusters/policy-spn-in-policy-overrides.json
  tests/unit/assessment/jobruns/gitsource_task.json
  tests/unit/assessment/jobruns/sql_tasks.json
  tests/unit/assessment/test_azure.py
  tests/unit/assessment/test_jobs.py
  tests/unit/hive_metastore/tables/external_src.json
  tests/unit/hive_metastore/tables/external_src_unsupported.json
  tests/unit/hive_metastore/tables/managed_dbfs.json
  tests/unit/hive_metastore/tables/managed_mnt.json
  tests/unit/hive_metastore/tables/managed_other.json
  tests/unit/hive_metastore/tables/view.json
Labels: ready to merge

#994 Added `databricks labs ucx cluster-remap` command to remap legacy cluster configurations to UC-compatible
  labs.yml
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/workspace_access/clusters.py
  tests/unit/test_cli.py
  tests/unit/workspace_access/test_clusters.py
Labels: ready to merge

#1123 Add assessment of interactive cluster usage compared to UC compute limitations
  docs/assessment.md
  src/databricks/labs/ucx/queries/assessment/interactive/00_0_interactive.md
  src/databricks/labs/ucx/queries/assessment/interactive/01_0_compute_access_mode_limitation_summary.sql
  src/databricks/labs/ucx/queries/assessment/interactive/02_0_cluster_summary.md
  src/databricks/labs/ucx/queries/assessment/interactive/03_0_cluster_summary.sql
  src/databricks/labs/ucx/queries/views/code_patterns_vw.sql
  src/databricks/labs/ucx/queries/views/misc_patterns_vw.sql
Labels: enhancement, step:assessment

#1110 Added external location validation when creating catalogs with `create-catalogs-schemas` command
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  tests/unit/hive_metastore/test_catalog_schema.py
  tests/unit/test_cli.py
Labels: CLI

#1080 [Experimental] Add support for permission migration API
  src/databricks/labs/ucx/mixins/fixtures.py
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/base.py
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/integration/workspace_access/test_generic.py
  tests/integration/workspace_access/test_redash.py
  tests/integration/workspace_access/test_scim.py
  tests/integration/workspace_access/test_secrets.py
  tests/performance/__init__.py
  tests/performance/conftest.py
  tests/performance/test_performance.py
  tests/unit/__init__.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/test_runtime.py
  tests/unit/workspace_access/test_manager.py
Labels: step:migrate groups

#1088 Adding flag to Job to identify Job submitted by jar
  src/databricks/labs/ucx/assessment/jobs.py
  tests/unit/assessment/jobruns/spark_jar_task.json
  tests/unit/assessment/jobs/spark-jar-task.json
  tests/unit/assessment/test_jobs.py
Labels: step:assessment

#1084 Skip installation if remote and local version is the same, provide prompt to override
  src/databricks/labs/ucx/install.py
  tests/integration/test_installation.py
  tests/unit/test_install.py
Labels: account-level work

#1135 Add ACL migration to `migrate-tables` workflow
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/runtime.py
  tests/integration/hive_metastore/test_migrate.py
  tests/unit/hive_metastore/test_table_migrate.py
Labels: do-not-merge

#1161 Use experimental Permissions Migration API also for Legacy Table ACLs
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/integration/test_installation.py
  tests/integration/workspace_access/test_generic.py
  tests/integration/workspace_access/test_redash.py
  tests/integration/workspace_access/test_scim.py
  tests/integration/workspace_access/test_secrets.py
  tests/integration/workspace_access/test_tacl.py
  tests/performance/test_performance.py
  tests/unit/test_runtime.py
  tests/unit/workspace_access/test_manager.py
Labels: step:migrate groups

#1077 Add Support for Migrating Table ACL of Interactive clusters using SPN
  src/databricks/labs/ucx/assessment/azure.py
  src/databricks/labs/ucx/hive_metastore/__init__.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/runtime.py
  src/databricks/labs/ucx/workspace_access/manager.py
  src/databricks/labs/ucx/workspace_access/tacl.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_grants.py
  tests/integration/hive_metastore/test_migrate.py
  tests/integration/test_installation.py
  tests/integration/workspace_access/test_groups.py
  tests/integration/workspace_access/test_tacl.py
  tests/unit/assessment/clusters/azure-spn-secret-interactive-multiple-spn.json
  tests/unit/assessment/test_azure.py
  tests/unit/hive_metastore/test_principal_grants.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/test_runtime.py
  tests/unit/workspace_access/test_tacl.py
Labels: credentials, ACL
