Repository databrickslabs/ucx, pull requests merged in 2024-04, with the labels that each got.

#1195 Add back prompts for table migration job cluster configuration
  src/databricks/labs/ucx/install.py
  tests/integration/test_installation.py
  tests/unit/test_install.py
Labels: do-not-merge

#1210 Support table migration to Unity Catalog in Python code
  src/databricks/labs/ucx/source_code/languages.py
  src/databricks/labs/ucx/source_code/pyspark.py
  tests/unit/source_code/test_pyspark.py
Labels: AST

#1226 Feature: Add troubleshooting guide
  README.md
  docs/troubleshooting.md
Labels: documentation

#1330 Add missing step sync-workspace-info
  README.md
Labels: cla-required

#1344 Refactor dependency graph
  src/databricks/labs/ucx/source_code/dependencies.py
  src/databricks/labs/ucx/source_code/notebook.py
  src/databricks/labs/ucx/source_code/notebook_migrator.py
  tests/unit/source_code/test_notebook.py
  tests/unit/source_code/test_notebook_migrator.py
Labels: ready to merge

#1417 Extend service principal migration with option to create access connectors with managed identity for each storage account
  pyproject.toml
  src/databricks/labs/ucx/azure/access.py
  src/databricks/labs/ucx/azure/credentials.py
  src/databricks/labs/ucx/azure/resources.py
  tests/integration/azure/test_credentials.py
  tests/integration/azure/test_resources.py
  tests/integration/conftest.py
  tests/unit/azure/azure/mappings.json
  tests/unit/azure/test_access.py
  tests/unit/azure/test_credentials.py
  tests/unit/azure/test_resources.py
Labels: ready to merge

#1441 Fix integration tests flakiness
  src/databricks/labs/ucx/installer/logs.py
  src/databricks/labs/ucx/mixins/fixtures.py
  tests/integration/conftest.py
  tests/integration/framework/test_fixtures.py
  tests/integration/hive_metastore/test_migrate.py
Labels: ready to merge

#1480 Refactor `WorkspaceInstaller` using service factory
  src/databricks/labs/ucx/install.py
  tests/integration/conftest.py
  tests/integration/test_installation.py
  tests/unit/assessment/test_dashboard.py
  tests/unit/test_install.py
Labels: tech debt
