Repository databrickslabs/ucx, pull requests merged in 2024-09, with the labels that each got.

#2520 Fix various `mypy`/`pylint`/`pytest` build warnings
  src/databricks/labs/ucx/source_code/linters/python_ast.py
  tests/integration/source_code/test_jobs.py
  tests/unit/azure/test_credentials.py
  tests/unit/mixins/test_cached_workspace_path.py
  tests/unit/source_code/linters/test_files.py
Labels: internal

#2524 Tech debt: clarify some grants crawler logic
  src/databricks/labs/ucx/hive_metastore/grants.py
  tests/unit/hive_metastore/test_grants.py
Labels: step/assessment, tech debt, migrate/access-control, internal

#2535 Remove unnecessary crawler API: `Mounts.inventorize_mounts()`
  src/databricks/labs/ucx/hive_metastore/locations.py
  tests/unit/hive_metastore/test_locations.py
Labels: internal

#2388 Integration tests: purge suffixes and `RemoveAfter` tags for fixtures that don't already have this
  src/databricks/labs/ucx/mixins/fixtures.py
Labels: internal

#2541 Bugfix: `test_delete_ws_groups_should_delete_renamed_and_reflected_groups_only`
  tests/integration/workspace_access/test_groups.py
Labels: bug, internal

#2402 Refactor: `CrawlerBase` and `PermissionsManager` snapshotting pattern
  src/databricks/labs/ucx/assessment/azure.py
  src/databricks/labs/ucx/assessment/clusters.py
  src/databricks/labs/ucx/assessment/init_scripts.py
  src/databricks/labs/ucx/assessment/jobs.py
  src/databricks/labs/ucx/assessment/pipelines.py
  src/databricks/labs/ucx/assessment/workflows.py
  src/databricks/labs/ucx/framework/crawlers.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/mapping.py
  src/databricks/labs/ucx/hive_metastore/migration_status.py
  src/databricks/labs/ucx/hive_metastore/table_size.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/udfs.py
  src/databricks/labs/ucx/recon/migration_recon.py
  src/databricks/labs/ucx/workspace_access/generic.py
  src/databricks/labs/ucx/workspace_access/groups.py
  src/databricks/labs/ucx/workspace_access/manager.py
  tests/integration/workspace_access/test_permissions_manager.py
  tests/integration/workspace_access/test_workflows.py
  tests/unit/assessment/test_workflows.py
  tests/unit/framework/test_crawlers.py
  tests/unit/workspace_access/test_manager.py
Labels: internal

#2477 Adds FasterTableScanCrawler for crawling tables faster in python
  src/databricks/labs/ucx/hive_metastore/tables.py
  tests/unit/hive_metastore/test_tables.py
Labels: internal

#2560 Document: clarify that the `assessment` job is not intended to be re-run.
  README.md
Labels: documentation

#2565 Re-merge: `CrawlerBase` and `FasterTableScanCrawler`
  src/databricks/labs/ucx/hive_metastore/tables.py
Labels: internal

#2546 Uses PermissionDenied instead of PermissionError
  src/databricks/labs/ucx/aws/access.py
  src/databricks/labs/ucx/installer/mixins.py
  tests/unit/aws/test_access.py
  tests/unit/install/test_install.py
Labels: internal

#2547 Refactors verify_timeout property on DeployedWorkflows
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/installer/workflows.py
  tests/integration/conftest.py
  tests/unit/install/test_install.py
  tests/unit/install/test_install_dashboards.py
  tests/unit/installer/test_workflows.py
Labels: internal

#2564 More escaping of SQL identifiers
  src/databricks/labs/ucx/assessment/azure.py
  src/databricks/labs/ucx/hive_metastore/migration_status.py
  tests/unit/recon/test_migration_recon.py
  tests/unit/test_factories.py
Labels: internal

#2566 Crawler snapshots: allow refreshing
  src/databricks/labs/ucx/framework/crawlers.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/workflows.py
  tests/integration/conftest.py
  tests/unit/assessment/test_clusters.py
  tests/unit/assessment/test_init_scripts.py
  tests/unit/assessment/test_jobs.py
  tests/unit/assessment/test_pipelines.py
  tests/unit/framework/test_crawlers.py
  tests/unit/hive_metastore/test_locations.py
  tests/unit/workspace_access/test_manager.py
Labels: enhancement, internal

#2590 fix typo
  tests/integration/hive_metastore/test_workflows.py
Labels: internal

#2592 Internal documentation: clarify the (different) purpose of the grant and permission crawlers
  src/databricks/labs/ucx/assessment/workflows.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/workspace_access/manager.py
Labels: documentation, internal

#2615 Fix failing integration test `test_reflect_account_groups_on_workspace_skips_groups_that_already_exists_in_the_workspace`
  tests/integration/workspace_access/test_groups.py
Labels: integration test failure, internal

#2604 [TECH DEBT]: Deal with some nits in the existing crawler code
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/tables.py
Labels: tech debt, internal

#2624 Fix failing integration test: `test_reflect_account_groups_on_workspace_skips_groups_that_already_exists_in_the_workspace`
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/integration/workspace_access/test_groups.py
Labels: migrate/groups, integration test failure

#2626 Retry create database on `InternalError`
  src/databricks/labs/ucx/install.py
Labels: feat/installer, internal

#2629 Fix test integration failure: `test_running_real_migrate_groups_job`
  tests/integration/workspace_access/test_workflows.py
Labels: integration test failure, internal

#2631 Integration test reliability: update some tests to ensure they use unique group names
  tests/integration/account/test_account.py
  tests/integration/framework/test_fixtures.py
Labels: internal

#2632 Reliability fix: `test_group_matching_names`
  tests/integration/workspace_access/test_groups.py
Labels: internal

#2657 Let `validate-groups-membership` command to run as collection
  labs.yml
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, migrate/groups, feat/cli

#2656 Let `migrate-dbsql-dashboards` command to run as collection
  labs.yml
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, migrate/redash, feat/cli, feat/migration-process

#2654 Let `migrate-tables` command run as collection
  labs.yml
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, migrate/jobs, feat/cli

#2652 Let `migrate-locations` command run as collection
  labs.yml
  src/databricks/labs/ucx/aws/locations.py
  src/databricks/labs/ucx/azure/locations.py
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, feat/cli

#2646 Drop replace methods with builtin
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/graph.py
  src/databricks/labs/ucx/source_code/notebooks/cells.py
  src/databricks/labs/ucx/source_code/notebooks/sources.py
  src/databricks/labs/ucx/source_code/python/python_analyzer.py
  tests/unit/source_code/test_base.py
  tests/unit/source_code/test_s3fs.py
Labels: internal

#2642 Assessment: crawl UDFs as a task in parallel to tables instead of implicitly during grants
  src/databricks/labs/ucx/assessment/workflows.py
Labels: enhancement, pr/do-not-merge, feat/crawler, step/assessment, feat/workflow

#2650 drop workspace path.stat() workaround
  src/databricks/labs/ucx/source_code/jobs.py
Labels: internal

#2665 Update `assessment` workflow documentation to cover the `crawl_udfs` task.
  README.md
  docs/ucx_assessment_workflow.png
Labels: documentation, internal

#2664 Let `migrate-acls` command run as collection
  labs.yml
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, feat/cli, migrate/access-control

#2653 Let `create-catalog-schemas` command run as collection
  labs.yml
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  tests/unit/test_cli.py
Labels: feat/account-level, feat/cli

#2649 Let `validate-external-locations` command run as collection
  labs.yml
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, feat/cli

#2640 Let `create-uber-principal` command run on collection of workspaces
  labs.yml
  src/databricks/labs/ucx/azure/access.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/contexts/workspace_cli.py
  tests/unit/test_cli.py
Labels: feat/account-level, feat/cli

#2647 Support multiple subscription ids for command line commands
  README.md
  labs.yml
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/contexts/workspace_cli.py
  tests/integration/conftest.py
  tests/unit/test_cli.py
  tests/unit/test_factories.py
Labels: feat/cli

#2677 Fix test failure: `test_workspace_object_crawler`
  tests/integration/assessment/test_assessment.py
Labels: internal

#2658 New workflow: `migration-progress-experimental`
  README.md
  docs/table_persistence.md
  labs.yml
  src/databricks/labs/ucx/assessment/workflows.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/framework/crawlers.py
  src/databricks/labs/ucx/progress/__init__.py
  src/databricks/labs/ucx/progress/workflows.py
  src/databricks/labs/ucx/runtime.py
  tests/integration/assessment/test_workflows.py
  tests/integration/progress/__init__.py
  tests/integration/progress/test_workflows.py
  tests/unit/progress/__init__.py
  tests/unit/progress/test_workflows.py
Labels: enhancement, feat/cli, feat/workflow

#2681 [internal] assign reviews to new group
  CODEOWNERS
  src/databricks/labs/ucx/mixins/fixtures.py
Labels: internal

#2683 [DOCUMENTATION] Improve documentation on using account profile for `sync-workspace-info` cli command
  README.md
Labels: documentation

#2684 Fast table crawler: suggestions/fixes for describing tables
  src/databricks/labs/ucx/hive_metastore/tables.py
  tests/unit/hive_metastore/test_tables.py
Labels: bug

#2690 [DOCUMENTATION] Improve documentation when installing UCX from a machine with restricted internet access
  README.md
  src/databricks/labs/ucx/install.py
Labels: documentation

#2692 Fix test failure: `test_running_real_remove_backup_groups_job`
  tests/integration/install/test_installation.py
  tests/integration/workspace_access/test_groups.py
Labels: migrate/groups, internal

#2697 Handle `InternalError` in `Listing.__iter__`
  src/databricks/labs/ucx/workspace_access/generic.py
  tests/unit/workspace_access/test_generic.py
Labels: migrate/access-control

#2694 Add `create-ucx-catalog` cli command
  Makefile
  README.md
  labs.yml
  src/databricks/labs/ucx/account/metastores.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/contexts/account_cli.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/source_code/queries.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_catalog_schema.py
  tests/unit/account/test_metastores.py
  tests/unit/conftest.py
  tests/unit/hive_metastore/test_catalog_schema.py
  tests/unit/install/test_install.py
  tests/unit/source_code/test_queries.py
  tests/unit/test_cli.py
  tests/unit/test_config.py
Labels: feat/cli, feat/migration-process

#2701 Harden configuration reading
  src/databricks/labs/ucx/assessment/secrets.py
  tests/unit/assessment/test_secrets.py
Labels: internal

#2579 Added Py4j implementation of tables crawler to retrieve a list of HMS tables in the assessment workflow
  docs/table_persistence.md
  src/databricks/labs/ucx/assessment/workflows.py
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/tables.scala
  src/databricks/labs/ucx/queries/assessment/main/01_4_table_crawl_failures.sql
  tests/integration/assessment/test_workflows.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/hive_metastore/test_tables.py
Labels: enhancement, pr/do-not-merge

#2753 Clone solacc repos 1 by 1 and delete them once linting is done
  tests/integration/source_code/solacc.py
Labels: internal

#2755 Documentation: table utilization updates
  docs/table_persistence.md
Labels: documentation, internal

#2760 Crawler: fix missing generic types on subclasses.
  src/databricks/labs/ucx/hive_metastore/table_size.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/udfs.py
Labels: ready to merge, internal
