Repository databrickslabs/ucx, pull requests merged in 2024-12, with the labels that each got.

#3394 Safe read files in more places
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/notebooks/sources.py
  tests/integration/source_code/test_base.py
  tests/unit/source_code/notebooks/test_sources.py
Labels: migrate/code

#3398 Add note about running assessment once
  README.md
Labels: documentation

#3378 Handle Databricks errors during workspace listings in the table migration status refresher
  src/databricks/labs/ucx/hive_metastore/table_migration_status.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_table_migration_status.py
Labels: step/assessment

#3407 Update sqlglot requirement from <25.33,>=25.5.0 to >=25.5.0,<25.34
  pyproject.toml
Labels: dependencies, internal

#3413 Update sqlglot requirement from <25.33,>=25.5.0 to >=25.5.0,<25.35
  pyproject.toml
Labels: dependencies

#3423 Ensure bugs are associated by default with the correct UCX project
  .github/ISSUE_TEMPLATE/bug.yml
Labels: internal

#3421 Fix integration test: `test_running_real_assessment_job_ext_hms`
  tests/integration/assessment/test_ext_hms.py
  tests/integration/hive_metastore/test_ext_hms.py
Labels: bug, bug/test-infra, internal

#3443 Log message as error when legacy permissions API is enabled/disabled depending on the workflow ran
  src/databricks/labs/ucx/workspace_access/workflows.py
Labels: migrate/groups

#3446 Exclude TACL migration in table migration integration tests
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_ext_hms.py
  tests/integration/hive_metastore/test_workflows.py
Labels: integration test failure, internal

#3442 Remove cached property from `JobProgressEncoder`
  src/databricks/labs/ucx/progress/jobs.py
Labels: tech debt, internal

#3459 Use LTS Databricks runtime version
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/installer/policy.py
  tests/integration/hive_metastore/test_workflows.py
  tests/integration/install/test_installation.py
Labels: integration test failure

#3464 Skip listing built-in catalogs to update table migration process
  src/databricks/labs/ucx/hive_metastore/table_migration_status.py
  tests/unit/hive_metastore/test_table_migration_status.py
Labels: feat/migration-index
