Repository databrickslabs/ucx, pull requests merged in 2024-11, with the labels that each got.

#3108 Fix Integration test failure of migration_tables
  tests/integration/hive_metastore/test_migrate.py
  tests/unit/source_code/test_directfs_access.py
Labels: bug

#3211 [DOC] README.md rewrite
  README.md
Labels: documentation

#3222 [DOC] Add dashboard section
  README.md
  src/databricks/labs/ucx/queries/assessment/azure/00_0_azure_service_principals.md
Labels: documentation

#3227 [internal] remove todo
  .github/workflows/acceptance.yml
Labels: internal

#3200 Speed up `update_migration_status` jobs by eliminating lots of redundant SQL queries
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
Labels: enhancement, feat/migration-index, tech debt, feat/migration-progress

#3240 [internal] Bring back disabled integration tests
  tests/integration/hive_metastore/test_table_move.py
Labels: internal

#3242 [internal] Added `debug_listing_upper_limit` to skip debug listing large workspaces
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/queries.py
Labels: internal

#3249 Fixed `test_experimental_permissions_migration_for_group_with_same_name` integration test failure
  tests/integration/install/test_installation.py
Labels: internal

#3254 Properly handle Python iterators together with `debug_listing_upper_limit` in slow tasks
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/queries.py
Labels: internal

#3317 Introduced `make_cluster_policy` and `make_cluster_policy_permissions` to `MockInstallation`
  tests/integration/assessment/test_workflows.py
  tests/integration/conftest.py
Labels: internal

#3310 Add hyperlink to database names in database summary dashboard
  src/databricks/labs/ucx/queries/assessment/main/10_0_database_summary.sql
Labels: ready to merge

#3269 Update `migration-progress-experimental` workflow to crawl tables from the `main` cluster
  src/databricks/labs/ucx/progress/workflows.py
Labels: bug

#3312 Pin Databricks SDK to minor version
  pyproject.toml
Labels: internal, pr/rebase

#3327 Update CODEOWNERS
  CODEOWNERS
Labels: internal

#3253 Move integration test to correct place
  pyproject.toml
  tests/integration/install/test_installation.py
  tests/integration/workspace_access/test_workflows.py
Labels: internal

#3250 [CHORE] Moving `QueryLinter` input objects to signature
  src/databricks/labs/ucx/assessment/workflows.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/progress/workflows.py
  src/databricks/labs/ucx/source_code/queries.py
  tests/integration/source_code/test_directfs_access.py
  tests/integration/source_code/test_queries.py
  tests/unit/progress/test_workflows.py
  tests/unit/source_code/test_queries.py
Labels: ready to merge, internal

#3270 Refactor refreshing of migration-status information for tables, eliminate another redundant refresh.
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/hive_metastore/table_migration_status.py
  src/databricks/labs/ucx/progress/history.py
  src/databricks/labs/ucx/progress/tables.py
  tests/unit/progress/test_tables.py
  tests/unit/progress/test_workflows.py
Labels: ready to merge, tech debt

#3332 Bump `databricks-sdk` and `databricks-labs-lsql` dependencies
  pyproject.toml
  tests/integration/conftest.py
  tests/integration/install/test_installation.py
Labels: upstream

#3331 Handle not parsing config in cli
  src/databricks/labs/ucx/cli.py
Labels: feat/cli, internal

#3333 Add migration progress documentation
  README.md
  docs/migration-progress.md
Labels: documentation

#3379 Tech debt: avoid caching with some test context properties
  tests/integration/conftest.py
Labels: tech debt, internal

#3373 Track `UsedTables` on `TableProgressEncoder`
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/progress/tables.py
  src/databricks/labs/ucx/source_code/base.py
  tests/integration/progress/test_tables.py
  tests/unit/progress/test_tables.py
  tests/unit/source_code/test_base.py
Labels: feat/migration-progress

#3375 Track `DirectFsAccess` on `JobsProgressEncoder`
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/progress/jobs.py
  src/databricks/labs/ucx/source_code/directfs_access.py
  tests/integration/conftest.py
  tests/integration/progress/test_jobs.py
  tests/unit/progress/test_jobs.py
Labels: feat/migration-progress

#3376 Handle non UTF-8 encoded notebook error explicitly
  src/databricks/labs/ucx/source_code/notebooks/loaders.py
  tests/unit/source_code/notebooks/test_loaders.py
Labels: migrate/code

#3382 Update sqlglot requirement from <25.32,>=25.5.0 to >=25.5.0,<25.33
  pyproject.toml
Labels: internal, upstream
