Repository databrickslabs/ucx, pull requests merged in 2024-07, with the labels that each got.

#1964 Adjust type hints in credentials handling for Azure API client
  src/databricks/labs/ucx/azure/resources.py
Labels: bug

#1944 Group renaming: wait for consistency before completing task
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/unit/workspace_access/test_groups.py
Labels: migrate/groups, python

#1941 Update README TOC
  README.md
Labels: internal

#1984 whitelist plotly
  src/databricks/labs/ucx/source_code/known.json
Labels: internal

#2089 Moved WorkspacePath to blueprint v0.7.0
  pyproject.toml
  src/databricks/labs/ucx/mixins/wspath.py
  src/databricks/labs/ucx/source_code/jobs.py
  tests/integration/mixins/__init__.py
  tests/integration/mixins/test_wspath.py
  tests/integration/source_code/test_jobs.py
Labels: internal

#1945 Revise integration test timeoutsIntegration test timeouts
  tests/integration/hive_metastore/test_migrate.py
  tests/integration/hive_metastore/test_workflows.py
  tests/integration/source_code/test_jobs.py
  tests/integration/test_installation.py
  tests/integration/test_runtime.py
  tests/integration/workspace_access/test_groups.py
Labels: integration test failure, bug/test-infra, internal

#2044 whitelist econml
  src/databricks/labs/ucx/source_code/known.json
Labels: ready to merge

#2100 Fix invalid JSON (`known.json`)
  src/databricks/labs/ucx/source_code/known.json
Labels: bug, internal

#2103 Improve integration test resiliency
  src/databricks/labs/ucx/mixins/fixtures.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_grant_detail.py
  tests/integration/hive_metastore/test_grants.py
  tests/integration/source_code/test_redash.py
  tests/integration/test_account.py
Labels: internal

#2111 Skip running certain integration tests when no relevant packages modified
  .github/workflows/nightly.yml
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/mixins/fixtures.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_grants.py
  tests/integration/hive_metastore/test_workflows.py
  tests/integration/source_code/test_jobs.py
  tests/integration/test_ext_hms.py
  tests/integration/test_installation.py
  tests/integration/test_runtime.py
  tests/unit/hive_metastore/test_tables.py
Labels: internal

#2115 Turn `modified_or_skip` into decorator
  src/databricks/labs/ucx/mixins/fixtures.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_catalog_schema.py
  tests/integration/hive_metastore/test_tables.py
  tests/integration/hive_metastore/test_workflows.py
  tests/integration/source_code/test_jobs.py
  tests/integration/test_ext_hms.py
  tests/integration/test_installation.py
  tests/integration/test_runtime.py
Labels: internal

#2118 Add pytest plugin for filtering of integration tests
  .github/workflows/acceptance.yml
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/known-readme.txt
  tests/integration/README.md
  tests/integration/account/__init__.py
  tests/integration/account/test_account.py
  tests/integration/assessment/test_ext_hms.py
  tests/integration/assessment/test_workflows.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_catalog_schema.py
  tests/integration/hive_metastore/test_ext_hms.py
  tests/integration/hive_metastore/test_tables.py
  tests/integration/hive_metastore/test_workflows.py
  tests/integration/install/__init__.py
  tests/integration/install/test_installation.py
  tests/integration/install/test_logs.py
  tests/integration/source_code/test_jobs.py
  tests/integration/test_ext_hms.py
  tests/integration/workspace_access/test_workflows.py
  tests/performance/conftest.py
  tests/performance/test_performance.py
Labels: internal

#2052 whitelist livereload
  src/databricks/labs/ucx/source_code/known.json
Labels: ready to merge

#2060 whitelist einops
  src/databricks/labs/ucx/source_code/known.json
Labels: ready to merge

#2123 Whitelist dbacademy
  src/databricks/labs/ucx/source_code/known.json
Labels: internal

#2129 Remove flaky tests
  tests/integration/assessment/test_ext_hms.py
  tests/integration/hive_metastore/test_workflows.py
  tests/integration/install/test_installation.py
Labels: internal

#2166 tentatively fix test_job_run_crawler
  tests/integration/assessment/test_jobs.py
Labels: internal

#2185 Check SQL formatting
  .github/workflows/push.yml
Labels: internal

#2187 [internal] script for retrieving list of workflows and commands
  pyproject.toml
  tests/integration/cmds.py
Labels: internal

#2188 Handle log folder does not exists
  src/databricks/labs/ucx/installer/workflows.py
  tests/unit/conftest.py
  tests/unit/installer/test_workflows.py
Labels: internal

#2200 Minor grammar corrections in logged warnings
  src/databricks/labs/ucx/source_code/jobs.py
  tests/unit/source_code/test_jobs.py
Labels: migrate/jobs, migrate/code, internal

#2206 Job integration tests: remove unused fixtures
  tests/integration/source_code/test_jobs.py
Labels: internal

#2199 Added support for DBFS when building the dependency graph for tasks
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/path_lookup.py
  tests/integration/source_code/test_jobs.py
  tests/unit/source_code/test_jobs.py
Labels: enhancement, migrate/jobs, migrate/code

#2215 Group migration: change error logging format
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/unit/workspace_access/test_workflows.py
Labels: enhancement, migrate/groups

#2225 Fix mypy flags `import distutils` in Python 3.12
  src/databricks/labs/ucx/source_code/python_libraries.py
Labels: internal

#2229 Update installation parallelization
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/installer/workflows.py
  tests/unit/test_install.py
Labels: internal

#2224 Fix create database in workspace installation
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/installer/workflows.py
  tests/unit/test_install.py
Labels: internal

#2233 Documentation spelling/copy improvements
  docs/assessment.md
Labels: documentation, internal

#2239 Group migration: additional logging
  src/databricks/labs/ucx/workspace_access/groups.py
Labels: enhancement

#2243 Rename `GraphBuilderContext` to `DependencyGraphContext` for clarity
  src/databricks/labs/ucx/source_code/graph.py
  src/databricks/labs/ucx/source_code/linters/files.py
  src/databricks/labs/ucx/source_code/notebooks/cells.py
  tests/unit/source_code/notebooks/test_cells.py
Labels: internal

#2247 Group migration: improve robustness while deleting workspace groups
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/integration/conftest.py
  tests/integration/install/test_installation.py
  tests/integration/workspace_access/test_groups.py
  tests/unit/workspace_access/test_groups.py
Labels: bug, enhancement, migrate/groups

#2272 Removed `@lru_cache` from `run_command`
  src/databricks/labs/ucx/framework/utils.py
Labels: internal

#2263 Group migration: improve robustness when renaming groups
  src/databricks/labs/ucx/workspace_access/groups.py
  tests/unit/workspace_access/test_groups.py
Labels: bug, enhancement, migrate/groups

#2274 Integration tests: purge suffix for more group fixtures
  tests/integration/conftest.py
Labels: internal

#2281 Mock WheelsV2 in unit-tests to avoid lengthy wheel-building.
  tests/unit/install/test_install_dashboards.py
Labels: internal

#2331 Fix tests that check the `RemoveAfter` tag values.
  tests/integration/framework/test_fixtures.py
Labels: bug, internal

#2333 New dashboard: group migration, showing groups that failed to migrate.
  src/databricks/labs/ucx/queries/migration/groups/00_0_migration_overview.md
  src/databricks/labs/ucx/queries/migration/groups/01_0_group_migration_failures.md
  src/databricks/labs/ucx/queries/migration/groups/01_1_group_migration_failures.sql
Labels: enhancement, migrate/groups
