Repository databrickslabs/ucx, pull requests merged in 2024-08, with the labels that each got.

#2344 Improve group migration error reporting
  src/databricks/labs/ucx/queries/migration/groups/00_0_migration_overview.md
  src/databricks/labs/ucx/queries/migration/groups/01_0_group_migration_failures.md
  src/databricks/labs/ucx/queries/migration/groups/01_1_group_migration_failures.sql
Labels: enhancement, migrate/groups

#2338 Update TODO about dashboard installation retry on `InternalError`
  src/databricks/labs/ucx/install.py
Labels: internal

#2347 Code Compatibility Dashboard: Fix broken links
  src/databricks/labs/ucx/queries/migration/main/02_0_code_compatibility_problems.md
  src/databricks/labs/ucx/queries/migration/main/02_1_code_compatibility_problems.sql
Labels: bug

#2357 Fix documentation typos: `create-missing-pricipals` -> `create-missing-principals`
  README.md
Labels: documentation

#2356 Rename for clarity
  src/databricks/labs/ucx/source_code/linters/files.py
Labels: internal

#2369 Integration tests: mark cluster policy fixtures with a purge-suffix
  src/databricks/labs/ucx/mixins/fixtures.py
Labels: bug, internal

#2387 Tech debt: simplify handling of the `spark_conf` and `libraries` arguments for the `make_job` integration test fixture
  src/databricks/labs/ucx/mixins/fixtures.py
Labels: internal

#2399 Remove `TODO` referring to #411 (won't do)
  src/databricks/labs/ucx/workspace_access/base.py
Labels: internal

#2349 Fix linting for Spark Python workflow tasks
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/source_code/graph.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/linters/files.py
  tests/integration/source_code/notebook_fake_python.py
  tests/integration/source_code/test_jobs.py
  tests/unit/source_code/conftest.py
  tests/unit/source_code/linters/test_files.py
  tests/unit/source_code/notebooks/test_cells.py
  tests/unit/source_code/test_dependencies.py
  tests/unit/source_code/test_graph.py
  tests/unit/source_code/test_jobs.py
  tests/unit/source_code/test_notebook.py
  tests/unit/source_code/test_path_lookup_simulation.py
  tests/unit/source_code/test_s3fs.py
Labels: bug, migrate/code

#2390 Optimisation: when detecting if a file is a notebook only read the start instead of the whole file
  src/databricks/labs/ucx/source_code/base.py
Labels: enhancement

#2341 Add `validate-table-locations` command for checking overlapping tables across workspaces
  README.md
  labs.yml
  src/databricks/labs/ucx/account/aggregate.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  tests/integration/account/test_aggregate.py
  tests/unit/account/test_aggregate.py
  tests/unit/hive_metastore/test_locations.py
Labels: ready to merge

#2392 Crawlers: Use `TRUNCATE TABLE` instead of `DELETE FROM` when resetting crawler tables.
  src/databricks/labs/ucx/framework/crawlers.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_workflows.py
Labels: enhancement

#2428 Fixed support for table/schema scope for the revert table cli command
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
Labels: bug

#2448 [internal] Fixed User-Agent error caused by SDK regression
  src/databricks/labs/ucx/__init__.py
Labels: internal

#2491 Don't draft automated releases
  .github/workflows/release.yml
Labels: internal

#2450 Enable `principal-prefix-access` command to run as collection
  labs.yml
  src/databricks/labs/ucx/azure/resources.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/install.py
  tests/unit/__init__.py
  tests/unit/test_cli.py
  tests/unit/test_collection.py
Labels: ready to merge

#2485 Always escape SQL identifiers
  src/databricks/labs/ucx/assessment/clusters.py
  src/databricks/labs/ucx/assessment/init_scripts.py
  src/databricks/labs/ucx/assessment/jobs.py
  src/databricks/labs/ucx/assessment/pipelines.py
  src/databricks/labs/ucx/framework/utils.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/table_size.py
  src/databricks/labs/ucx/hive_metastore/view_migrate.py
  src/databricks/labs/ucx/workspace_access/generic.py
  src/databricks/labs/ucx/workspace_access/groups.py
  src/databricks/labs/ucx/workspace_access/manager.py
  tests/integration/hive_metastore/test_migrate.py
  tests/integration/recon/__init__.py
  tests/unit/assessment/test_workflows.py
  tests/unit/azure/test_access.py
  tests/unit/azure/test_locations.py
  tests/unit/framework/test_utils.py
  tests/unit/hive_metastore/test_catalog_schema.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/hive_metastore/test_locations.py
  tests/unit/hive_metastore/test_mapping.py
  tests/unit/hive_metastore/test_migrate_acls.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_table_move.py
  tests/unit/hive_metastore/test_table_size.py
  tests/unit/hive_metastore/test_tables.py
  tests/unit/hive_metastore/test_udfs.py
  tests/unit/hive_metastore/test_view_migrate.py
  tests/unit/hive_metastore/test_views_sequencer.py
  tests/unit/hive_metastore/test_workflows.py
  tests/unit/test_cli.py
  tests/unit/workspace_access/test_manager.py
  tests/unit/workspace_access/test_tacl.py
  tests/unit/workspace_access/test_workflows.py
Labels: internal

#2500 Fix failing test `test_migrate_managed_tables_with_acl`
  tests/integration/hive_metastore/test_migrate.py
Labels: internal

#2501 Resolve open TODO about retry on errors deployed during Lakeview dashboard deployment
  src/databricks/labs/ucx/install.py
Labels: internal

#2502 Implement dependency graph walker
  src/databricks/labs/ucx/source_code/graph.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/linters/files.py
Labels: internal

#2506 Refactor linters
  src/databricks/labs/ucx/account/aggregate.py
  src/databricks/labs/ucx/hive_metastore/view_migrate.py
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/linters/context.py
  src/databricks/labs/ucx/source_code/linters/dbfs.py
  src/databricks/labs/ucx/source_code/linters/imports.py
  src/databricks/labs/ucx/source_code/linters/pyspark.py
  src/databricks/labs/ucx/source_code/linters/spark_connect.py
  src/databricks/labs/ucx/source_code/linters/table_creation.py
  src/databricks/labs/ucx/source_code/notebooks/cells.py
  src/databricks/labs/ucx/source_code/queries.py
  src/databricks/labs/ucx/source_code/redash.py
  tests/unit/source_code/linters/test_dbfs.py
  tests/unit/source_code/linters/test_pyspark.py
  tests/unit/source_code/linters/test_python_imports.py
  tests/unit/source_code/linters/test_spark_connect.py
  tests/unit/source_code/linters/test_table_creation.py
  tests/unit/source_code/test_notebook.py
  tests/unit/source_code/test_queries.py
Labels: internal
