Repository databrickslabs/ucx, pull requests merged in 2024-02, with the labels that each got.

#853 Creates cluster policy (ucx-policy) to be used by all UCX compute
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/install.py
  tests/integration/test_installation.py
  tests/unit/test_install.py
Labels: ready to merge, breaking change

#929 Prepare for running integration tests via common GitHub action
  .codegen.json
Labels: do-not-merge

#763 Add a command to create account level groups if they do not exist
  README.md
  labs.yml
  src/databricks/labs/ucx/account.py
  src/databricks/labs/ucx/cli.py
  tests/integration/test_account.py
  tests/unit/test_account.py
  tests/unit/test_cli.py
Labels: enhancement
