Repository databrickslabs/ucx, pull requests merged in 2024-10, with the labels that each got.

#2754 Add and populate UCX `workflow_runs` table
  README.md
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/contexts/workspace_cli.py
  src/databricks/labs/ucx/installer/workflows.py
  src/databricks/labs/ucx/progress/install.py
  src/databricks/labs/ucx/progress/workflow_runs.py
  src/databricks/labs/ucx/progress/workflows.py
  tests/integration/conftest.py
  tests/integration/progress/test_install.py
  tests/integration/progress/test_workflow_runs.py
  tests/integration/progress/test_workflows.py
  tests/unit/progress/test_install.py
  tests/unit/progress/test_workflow_runs.py
  tests/unit/test_cli.py
Labels: feat/workflow, feat/migration-process

#2788 Clean up for workspace scan tables
  tests/integration/progress/test_workflows.py
  tests/unit/contexts/test_workflow_task.py
Labels: tech debt, internal

#2807 Fix "too many values to unpack" error in integration tests
  tests/integration/source_code/test_jobs.py
Labels: integration test failure, internal

#2817 Fix integration issue when collecting tables
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/source_code/linters/pyspark.py
Labels: pr/do-not-merge

#2814 Fix failure: `test_table_size_crawler`
  tests/unit/hive_metastore/test_table_size.py
Labels: internal

#2809 Fix missing arguments to `WorkflowLinter`
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/source_code/used_table.py
  tests/unit/contexts/test_application.py
Labels: integration test failure, internal

#2813 [TECH DEBT] Add type hints for cached properties
  src/databricks/labs/ucx/account/aggregate.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/contexts/account_cli.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/contexts/workspace_cli.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/source_code/known.py
  src/databricks/labs/ucx/source_code/python_libraries.py
  src/databricks/labs/ucx/workspace_access/generic.py
  tests/integration/conftest.py
Labels: tech debt, internal

#2835 collect used tables as part of running report
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/source_code/queries.py
  tests/integration/source_code/test_queries.py
  tests/unit/source_code/test_queries.py
Labels: internal

#2856 Unit test updates: workspace client fixture (`ws`)
  tests/integration/workspace_access/test_permissions_manager.py
  tests/unit/__init__.py
  tests/unit/account/test_aggregate.py
  tests/unit/conftest.py
  tests/unit/hive_metastore/test_migrate_acls.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/recon/test_migration_recon.py
  tests/unit/test_collection.py
Labels: internal

#2855 Type hint unit tests, drop unused mock, resolve linting issues.
  tests/unit/workspace_access/test_tacl.py
Labels: internal

#2852 Replace `greenlit` with unknown library in integration tests
  tests/integration/source_code/test_jobs.py
Labels: integration test failure, internal

#2861 Make delta format case sensitive
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/queries/assessment/main/10_0_database_summary.sql
  src/databricks/labs/ucx/queries/assessment/main/10_1_all_tables.sql
  src/databricks/labs/ucx/queries/views/objects.sql
  src/databricks/labs/ucx/queries/views/table_estimates.sql
  tests/unit/hive_metastore/test_locations.py
  tests/unit/hive_metastore/test_tables.py
Labels: migrate/external

#2862 Make delta format case sensitive
  src/databricks/labs/ucx/queries/views/table_estimates.sql
Labels: migrate/external

#2815 Limit resources to assess in integration tests that run the `assessment` workflow
  src/databricks/labs/ucx/contexts/workflow_task.py
  tests/integration/assessment/test_ext_hms.py
  tests/integration/assessment/test_workflows.py
  tests/integration/conftest.py
  tests/integration/progress/test_workflows.py
Labels: integration test failure, internal

#2863 Upgrade minimum required version of `pytester`: 0.2.1 → 0.3.0
  pyproject.toml
Labels: dependencies, internal

#2851 Verify UCX catalog is accessible at start of `migration-progress-experimental` workflow
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/hive_metastore/verification.py
  src/databricks/labs/ucx/installer/workflows.py
  src/databricks/labs/ucx/progress/workflows.py
  tests/unit/conftest.py
  tests/unit/contexts/test_application.py
  tests/unit/hive_metastore/test_verification.py
  tests/unit/progress/test_workflows.py
Labels: feat/migration-process

#2553 Added export CLI functionality for assessment results
  README.md
  labs.yml
  src/databricks/labs/ucx/assessment/export.py
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/installer/workflows.py
  tests/unit/assessment/test_export.py
  tests/unit/test_cli.py
Labels: ready to merge

#2872 Use acceptance v0.3.0
  .github/workflows/acceptance.yml
  .github/workflows/nightly.yml
Labels: internal

#2869 Fix test failure: `test_migrate_external_table_failed_sync`
  tests/integration/hive_metastore/test_migrate.py
Labels: integration test failure, internal

#2819 Adds type hints with `TablesCrawler` for the table crawlers where required #2819
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/tables.py
Labels: internal

#2877 Handle `PermissionDenied` when retrieving `WorkspaceClient`s from account
  src/databricks/labs/ucx/account/workspaces.py
  tests/unit/account/test_workspaces.py
Labels: feat/account-level, feat/cli

#2853 Update linter integration tests to ensure notebook source is linted
  tests/integration/source_code/test_jobs.py
Labels: bug, internal

#2865 Avoid resource conflicts in integration tests by using a random dir name
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_migrate.py
  tests/integration/hive_metastore/test_table_move.py
Labels: pr/do-not-merge

#2812 More tests
  tests/integration/assessment/test_workflows.py
  tests/unit/source_code/test_jobs.py
Labels: internal

#2774 Crawler: support for object ownership
  src/databricks/labs/ucx/assessment/clusters.py
  src/databricks/labs/ucx/assessment/jobs.py
  src/databricks/labs/ucx/assessment/pipelines.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/framework/crawlers.py
  src/databricks/labs/ucx/framework/owners.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/table_migration_status.py
  src/databricks/labs/ucx/hive_metastore/table_size.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/udfs.py
  src/databricks/labs/ucx/source_code/directfs_access.py
  tests/integration/assessment/test_clusters.py
  tests/integration/assessment/test_jobs.py
  tests/integration/assessment/test_pipelines.py
  tests/integration/framework/test_owners.py
  tests/integration/hive_metastore/test_grants.py
  tests/integration/hive_metastore/test_table_migrate.py
  tests/integration/hive_metastore/test_tables.py
  tests/integration/hive_metastore/test_udfs.py
  tests/integration/source_code/test_directfs_access.py
  tests/unit/assessment/test_clusters.py
  tests/unit/assessment/test_jobs.py
  tests/unit/assessment/test_pipelines.py
  tests/unit/framework/test_owners.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_table_size.py
  tests/unit/hive_metastore/test_tables.py
  tests/unit/hive_metastore/test_udfs.py
  tests/unit/source_code/test_directfs_access.py
  tests/unit/workspace_access/test_manager.py
Labels: enhancement, ready to merge

#2884 Integration test update: `test_fallback_admin_user`
  tests/integration/framework/test_owners.py
Labels: internal

#2885 Tech debt: fix situations where `next()` isn't being used properly
  src/databricks/labs/ucx/source_code/linters/imports.py
  src/databricks/labs/ucx/source_code/notebooks/cells.py
  src/databricks/labs/ucx/source_code/path_lookup.py
  tests/unit/hive_metastore/test_table_migrate.py
Labels: bug, tech debt

#2744 Add UCX history schema and table for storing UCX's artifact
  src/databricks/labs/ucx/progress/install.py
  tests/integration/progress/test_install.py
  tests/unit/progress/test_install.py
Labels: feat/cli, feat/migration-process

#2898 Improve creating UC catalogs
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  tests/unit/hive_metastore/test_catalog_schema.py
  tests/unit/test_cli.py
Labels: feat/cli

#2914 Remove duplicate "`export-assessment` command" section in README
  README.md
Labels: documentation, tech debt

#2912 Verify migration progress prerequisites during UCX catalog creation
  src/databricks/labs/ucx/cli.py
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/progress/install.py
  src/databricks/labs/ucx/progress/workflows.py
  tests/unit/progress/test_install.py
  tests/unit/progress/test_workflows.py
  tests/unit/test_cli.py
Labels: feat/cli, feat/migration-process

#2915 Document preparing external locations when creating catalogs
  README.md
Labels: documentation

#2917 Improve logging when skipping grant a in `create-catalogs-schemas`
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  tests/unit/hive_metastore/test_catalog_schema.py
Labels: tech debt

#2920 Fixed absolute path normalisation in source code analysis
  src/databricks/labs/ucx/source_code/notebooks/loaders.py
  tests/integration/source_code/test_cells.py
Labels: ready to merge

#2924 Fixed `OSError: [Errno 95]` bug in `assess_workflows` task by skipping GIT-sourced workflows from static code analysis
  src/databricks/labs/ucx/source_code/jobs.py
Labels: ready to merge

#2892 Fix issue with migrating MANAGED hive_metastore table to UC
  README.md
  src/databricks/labs/ucx/config.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/install.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_migrate.py
  tests/integration/install/test_installation.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_tables.py
  tests/unit/install/test_install.py
Labels: ready to merge

#2936 Comment code
  src/databricks/labs/ucx/source_code/path_lookup.py
Labels: internal

#2937 Revert workaround for #2887
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/linters/pyspark.py
  tests/unit/source_code/samples/functional/table-access.py
  tests/unit/source_code/samples/functional/table-access.sql
Labels: internal

#2933 Improve logging when skipping legacy grant in `create-catalogs-schemas`
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  tests/unit/hive_metastore/test_catalog_schema.py
Labels: tech debt

#2940 Set UsedTable.is_read/is_write for spark calls
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/linters/pyspark.py
  tests/unit/source_code/test_context.py
Labels: internal

#2938 [chore] retrofit missing type annotations in `source_code` package and fix some hidden bugs
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/directfs_access.py
  src/databricks/labs/ucx/source_code/graph.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/known.py
  src/databricks/labs/ucx/source_code/linters/directfs.py
  src/databricks/labs/ucx/source_code/linters/files.py
  src/databricks/labs/ucx/source_code/linters/from_table.py
  src/databricks/labs/ucx/source_code/linters/imports.py
  src/databricks/labs/ucx/source_code/linters/pyspark.py
  src/databricks/labs/ucx/source_code/linters/spark_connect.py
  src/databricks/labs/ucx/source_code/notebooks/cells.py
  src/databricks/labs/ucx/source_code/notebooks/loaders.py
  src/databricks/labs/ucx/source_code/notebooks/magic.py
  src/databricks/labs/ucx/source_code/notebooks/migrator.py
  src/databricks/labs/ucx/source_code/notebooks/sources.py
  src/databricks/labs/ucx/source_code/path_lookup.py
  src/databricks/labs/ucx/source_code/python/python_analyzer.py
  src/databricks/labs/ucx/source_code/python/python_ast.py
  src/databricks/labs/ucx/source_code/python/python_infer.py
  src/databricks/labs/ucx/source_code/python_libraries.py
  src/databricks/labs/ucx/source_code/queries.py
  src/databricks/labs/ucx/source_code/redash.py
  src/databricks/labs/ucx/source_code/sql/__init__.py
  src/databricks/labs/ucx/source_code/sql/sql_parser.py
  tests/unit/source_code/linters/test_directfs.py
  tests/unit/source_code/linters/test_files.py
  tests/unit/source_code/linters/test_from_table.py
  tests/unit/source_code/linters/test_linters.py
  tests/unit/source_code/linters/test_pyspark.py
  tests/unit/source_code/linters/test_python_imports.py
  tests/unit/source_code/linters/test_spark_connect.py
  tests/unit/source_code/linters/test_table_creation.py
  tests/unit/source_code/notebooks/test_cells.py
  tests/unit/source_code/notebooks/test_loader.py
  tests/unit/source_code/notebooks/test_sources.py
  tests/unit/source_code/python/test_python_ast.py
  tests/unit/source_code/sql/__init__.py
  tests/unit/source_code/sql/test_sql_parser.py
  tests/unit/source_code/test_base.py
  tests/unit/source_code/test_dependencies.py
  tests/unit/source_code/test_directfs_access.py
  tests/unit/source_code/test_functional.py
  tests/unit/source_code/test_graph.py
  tests/unit/source_code/test_jobs.py
  tests/unit/source_code/test_known.py
  tests/unit/source_code/test_lsp_plugin.py
  tests/unit/source_code/test_notebook_linter.py
  tests/unit/source_code/test_path_lookup.py
  tests/unit/source_code/test_path_lookup_simulation.py
  tests/unit/source_code/test_python_libraries.py
  tests/unit/source_code/test_queries.py
  tests/unit/source_code/test_redash.py
  tests/unit/source_code/test_s3fs.py
  tests/unit/source_code/test_used_table.py
Labels: internal

#2950 Dependency update: ensure we install with at least version 0.9.1 of `databricks-labs-blueprint`
  pyproject.toml
Labels: dependencies

#2941 `create-uber-principal` fixes and improvements
  src/databricks/labs/ucx/azure/access.py
  tests/integration/azure/test_access.py
  tests/unit/azure/__init__.py
  tests/unit/azure/test_access.py
  tests/unit/azure/test_resources.py
  tests/unit/test_cli.py
Labels: bug, cloud/azure, feat/cli

#2958 Fix #2902
  tests/integration/assessment/test_workflows.py
Labels: internal

#2954 Make `ExternalLocations` explicitly depend on `TablesCrawler` and `MountsCrawler`
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/hive_metastore/__init__.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/workflows.py
  tests/integration/aws/test_access.py
  tests/integration/aws/test_credentials.py
  tests/integration/azure/test_credentials.py
  tests/integration/azure/test_locations.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_external_locations.py
  tests/integration/hive_metastore/test_federation.py
  tests/integration/hive_metastore/test_migrate.py
  tests/unit/assessment/test_workflows.py
  tests/unit/aws/test_access.py
  tests/unit/azure/test_access.py
  tests/unit/azure/test_locations.py
  tests/unit/hive_metastore/test_locations.py
  tests/unit/hive_metastore/test_principal_grants.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_tables.py
  tests/unit/test_cli.py
Labels: internal

#2962 Clarify `skip` and `unskip` commands work on views
  README.md
  labs.yml
  src/databricks/labs/ucx/cli.py
  tests/unit/test_cli.py
Labels: documentation, feat/cli

#2978 simplify code of airflow job detection
  src/databricks/labs/ucx/assessment/jobs.py
Labels: internal

#2953 Update the workspace content cache used during linting
  src/databricks/labs/ucx/mixins/cached_workspace_path.py
  src/databricks/labs/ucx/source_code/base.py
  src/databricks/labs/ucx/source_code/jobs.py
  src/databricks/labs/ucx/source_code/notebooks/sources.py
  tests/unit/mixins/test_cached_workspace_path.py
  tests/unit/source_code/notebooks/test_sources.py
  tests/unit/source_code/test_jobs.py
Labels: internal

#2966 improve type hints
  src/databricks/labs/ucx/assessment/azure.py
  src/databricks/labs/ucx/assessment/jobs.py
Labels: internal

#2985 [chore] use specific assertions for external location verification
  tests/integration/hive_metastore/test_external_locations.py
Labels: internal

#2984 Warn when table has column without no name during table migration
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  tests/unit/hive_metastore/test_table_migrate.py
Labels: bug, migrate/external, migrate/managed

#2955 Let `create-catalogs-schemas` reuse `MigrateGrants` so that it applies group renaming
  src/databricks/labs/ucx/contexts/application.py
  src/databricks/labs/ucx/hive_metastore/catalog_schema.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/mapping.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  tests/integration/hive_metastore/test_catalog_schema.py
  tests/unit/hive_metastore/test_catalog_schema.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/hive_metastore/test_mapping.py
  tests/unit/hive_metastore/test_migrate_acls.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/test_cli.py
Labels: bug, ready to merge, migrate/access-control

#3001 Unit test fix: restore monkey-patched `datetime` when test finishes
  tests/unit/hive_metastore/test_table_migrate.py
Labels: tech debt, internal

#2997 Skip applying permissions for workspace system groups to Unity Catalog resources
  src/databricks/labs/ucx/hive_metastore/grants.py
  tests/integration/conftest.py
  tests/integration/hive_metastore/test_catalog_schema.py
  tests/unit/hive_metastore/test_principal_grants.py
Labels: ready to merge, migrate/access-control

#2982 Return `False` when failed to migrate table
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/table_migration_status.py
Labels: bug, migrate/managed, internal

#3004 Remove a dead (ownership-related) class
  src/databricks/labs/ucx/framework/owners.py
Labels: internal

#3024 Handle installing libraries multiple times in `PipResolver`
  src/databricks/labs/ucx/source_code/python_libraries.py
  tests/integration/source_code/test_libraries.py
  tests/unit/source_code/samples/pip_install_pytest_twice.py
Labels: migrate/code

#3025 Update migration progress workflow to also re-lint dashboards and jobs
  docs/table_persistence.md
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/progress/workflows.py
  tests/unit/progress/test_workflows.py
Labels: enhancement

#3034 Ensure that pipeline assessment doesn't fail if a pipeline is deleted…
  src/databricks/labs/ucx/assessment/pipelines.py
  tests/unit/assessment/test_pipelines.py
Labels: bug

#3046 Fixed snapshot loading for DFSA and used-table crawlers
  src/databricks/labs/ucx/source_code/directfs_access.py
  src/databricks/labs/ucx/source_code/used_table.py
  tests/integration/source_code/test_jobs.py
  tests/unit/source_code/test_queries.py
Labels: bug

#3068 Tech debt: let `HistoryEncoding` work with string-based type annotations in addition to the normal type-based ones
  src/databricks/labs/ucx/progress/history.py
  tests/unit/progress/test_history.py
Labels: bug, internal

#2767 Improve scan tables in mounts
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/source_code/known.json
  tests/unit/hive_metastore/test_locations.py
Labels: pr/do-not-merge, pr/rebase

#3071 Consistently use `sql_backend` and `tables_crawler` everywhere for properties and constructor argument names
  src/databricks/labs/ucx/assessment/azure.py
  src/databricks/labs/ucx/assessment/clusters.py
  src/databricks/labs/ucx/assessment/init_scripts.py
  src/databricks/labs/ucx/assessment/jobs.py
  src/databricks/labs/ucx/assessment/pipelines.py
  src/databricks/labs/ucx/framework/crawlers.py
  src/databricks/labs/ucx/hive_metastore/grants.py
  src/databricks/labs/ucx/hive_metastore/locations.py
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/table_migration_status.py
  src/databricks/labs/ucx/hive_metastore/table_move.py
  src/databricks/labs/ucx/hive_metastore/table_size.py
  src/databricks/labs/ucx/hive_metastore/tables.py
  src/databricks/labs/ucx/hive_metastore/udfs.py
  src/databricks/labs/ucx/recon/migration_recon.py
  src/databricks/labs/ucx/source_code/directfs_access.py
  src/databricks/labs/ucx/source_code/used_table.py
  src/databricks/labs/ucx/workspace_access/generic.py
  src/databricks/labs/ucx/workspace_access/groups.py
  src/databricks/labs/ucx/workspace_access/manager.py
  tests/integration/assessment/test_clusters.py
  tests/integration/assessment/test_jobs.py
  tests/integration/assessment/test_pipelines.py
  tests/unit/framework/test_crawlers.py
Labels: internal

#3073 Rename `HistoryLog` into `ProgressEncoder`
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/progress/history.py
  src/databricks/labs/ucx/progress/jobs.py
  src/databricks/labs/ucx/progress/workflows.py
  tests/unit/assessment/test_clusters.py
  tests/unit/assessment/test_jobs.py
  tests/unit/assessment/test_pipelines.py
  tests/unit/hive_metastore/test_grants.py
  tests/unit/hive_metastore/test_table_migrate.py
  tests/unit/hive_metastore/test_tables.py
  tests/unit/hive_metastore/test_udfs.py
  tests/unit/progress/test_history.py
  tests/unit/progress/test_workflows.py
Labels: internal

#3078 Snooze faulty integration tests introduced by #2892
  tests/integration/hive_metastore/test_migrate.py
Labels: bug, internal

#3079 Add grant progress encoder
  src/databricks/labs/ucx/progress/grants.py
  tests/unit/progress/test_grants.py
Labels: feat/migration-progress

#3077 Fix solacc failure
  src/databricks/labs/ucx/source_code/linters/files.py
  tests/integration/source_code/solacc.py
Labels: internal

#3089 [TECH DEBT] Code clean up in cluster module
  src/databricks/labs/ucx/assessment/clusters.py
Labels: tech debt, internal

#3083 Add table progress encoder
  src/databricks/labs/ucx/contexts/workflow_task.py
  src/databricks/labs/ucx/progress/grants.py
  src/databricks/labs/ucx/progress/tables.py
  src/databricks/labs/ucx/progress/workflows.py
  tests/unit/progress/test_grants.py
  tests/unit/progress/test_tables.py
  tests/unit/progress/test_workflows.py
Labels: feat/migration-progress

#3016 Add dashboard for tracking migration progress
  src/databricks/labs/ucx/install.py
  src/databricks/labs/ucx/progress/install.py
  src/databricks/labs/ucx/queries/progress/main/00_0_migration_progress.md
  src/databricks/labs/ucx/queries/progress/main/01_0_percentage_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_1_percentage_udf_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_2_percentage_grant_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_3_percentage_job_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_4_percentage_cluster_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_5_percentage_table_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_6_percentage_pipeline_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_7_percentage_policy_migration_progress.sql
  src/databricks/labs/ucx/queries/progress/main/01_8_distinct_failures_per_object_type.sql
  src/databricks/labs/ucx/queries/progress/main/02_0_migration_status_of_tables_and_views.md
  src/databricks/labs/ucx/queries/progress/main/02_0_owner.filter.yml
  src/databricks/labs/ucx/queries/progress/main/02_1_pending_migration_data_objects.sql
  src/databricks/labs/ucx/queries/progress/main/02_2_migration_status_by_owner_bar_graph.sql
  src/databricks/labs/ucx/queries/progress/main/02_3_migrated_data_objects.sql
  src/databricks/labs/ucx/queries/progress/main/02_4_migration_status_by_owner_overview.sql
  src/databricks/labs/ucx/queries/views/objects_snapshot.sql
  tests/integration/queries/__init__.py
  tests/integration/queries/test_migration_progress.py
Labels: feat/viz, feat/migration-progress

#3109 [chore] improve unit test coverage
  pyproject.toml
  src/databricks/labs/ucx/source_code/linters/directfs.py
  src/databricks/labs/ucx/source_code/python/python_ast.py
  tests/unit/source_code/test_directfs_access.py
Labels: internal
