Repository databrickslabs/ucx, pull requests merged in 2024-01, with the labels that each got.

#773 Update databricks-sdk requirement from ~=0.16.0 to ~=0.17.0
  pyproject.toml
  src/databricks/labs/ucx/framework/dashboards.py
  tests/unit/assessment/test_dashboard.py
Labels: dependencies

#777 Fixing move table command to delete table/view regardless if permissions are present, skipping corrupted tables when crawling table size and making existing tests more stable
  src/databricks/labs/ucx/hive_metastore/table_migrate.py
  src/databricks/labs/ucx/hive_metastore/table_size.py
  tests/integration/hive_metastore/test_table_move.py
  tests/unit/hive_metastore/test_table_move.py
  tests/unit/hive_metastore/test_table_size.py
Labels: bug

#806 Document the assessment report
  docs/assessment.md
Labels: documentation, enhancement
