Repository databrickslabs/ucx, pull requests merged in 2025-07, with the labels that each got.

#4209 Handle PermisssionDenied exception so that a new dashboard is created.
  src/databricks/labs/ucx/install.py
Labels: bug

#4206 Add a fix for notebook ownership integration test
  tests/integration/framework/test_owners.py
Labels: tech debt

#4228 Freshen documentation (docusaurus) dependencies
  docs/ucx/yarn.lock
Labels: documentation, internal, dependencies
